# Derin Ogrenme Egitimi Soru Sayfası

Merhaba değerli katılımcı, kursa başvurun için ilk önce bu repoyu bilgisayarına indirip jupyter notebook ile çalıştırman gerekiyor, bu işlemleri tamamlaman için sana hiçbir yönerge vermiyoruz, çünkü burada amacımız hali hazırda senin bu işlemleri bilip bilmediğini yahut bunları kendi başına öğrenebiliyor musun buna bakmak. Hazırsan senin için de her şeyi hazırladık.


Bu test sayfası bir akış halinde hazırlandı, cevaplayabildiğin soruları cevapladıktan sonra kaydedip bize göndermen gerekiyor.
Hepsini tamamlamak zorunda değilsin, fakat yapamadığın kısımlar üzerinde araştırarak yeni şeylere ne kadar iyi adapte oluyorsun bunu da görmüş olacaksın.

Eğer şuan buradaysan zaten yolun büyük bir kısmını halletmişsin demektir, dosyanı sağ üst taraftaki file menüsünde "download as" sekmesinden ".ipynb" uzantılı olarak indirdikten sonra [Uludag Deep Learning mail adresi](mailto:uludagdeeplearning@gmail.com) gönderebilirsin. Eğer github sayfası açıp ödevini oraya yükledikten sonra ilgili linki bize gönderirsen ekstra puan alacaksın. 

Ödevin son kısmında opsiyonel bir bölüm daha var, gerçekten zor bir bölüm olduğundan emin olabilirsin, son bölümü seçiciliği artırmak için koyuyoruz, şayet çözersen bu senin için ekstra puan demek.

Buradaki her bir satıra hücre deniyor, shift+enter kombinasyonuyla hücreleri çalıştırabilirsin. "Sen zaten bunu biz söylemeden de basitçe çözebilirdin."

In [1]:
isim = input("Isminizi Girin= ")

Isminizi Girin= Ahmet Can Gümüş


In [2]:
print("Hosgeldin {}, öncelikle burada olduğun için çok mutluyuz, seni bu test ile karşılaştırdığımız için biz de üzgünüz fakat adil bir seçim yapmamız gerekiyor.".format(isim))

Hosgeldin Ahmet Can Gümüş, öncelikle burada olduğun için çok mutluyuz, seni bu test ile karşılaştırdığımız için biz de üzgünüz fakat adil bir seçim yapmamız gerekiyor.


## Python

In [3]:
#İleri kullanacağımız fonksiyonlar için bu hücreyi çalıştırın

import numpy as np
import math

### Soru 0:

Python Versiyonunuzu Yazdırın.

In [4]:
#Kodun buraya gelecek
import sys
print(sys.version)

3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)]


### Soru 1:

Telefon numaranızın son hanesindeki rakamdan başlayarak, son iki hanesindeki sayıya kadar devam eden bir liste oluşturun, bu listedeki sayıların ortalamasını ve toplamını yazdırın. (son iki hane sayısı 10'dan küçük olanlar için verilecek değer 70'dir.)

In [5]:
no = int(input("Telefon Numarınızı Girin= "))

Telefon Numarınızı Girin= 05366366417


### Cevap 1:

In [6]:
b=list (range(7,18))
toplam = 0
for i in b :
    toplam = toplam + i
 
print('Listedeki sayıların toplamı:',toplam)
print('Listedeki sayıların ortalaması:',toplam / len(b))

Listedeki sayıların toplamı: 132
Listedeki sayıların ortalaması: 12.0


### Soru 2:

Alt satırdaki yazi degiskeni olan hücreyi çalıştırın ve for döngüsüyle bu yazının her harfini bir listeye eleman olarak aktarın.

Not: Boşluklar ve noktalama işaretlerini listeye almamalısınız.

In [148]:
yazi = "uludag deeplearning teknik bir topluluktur."

### Cevap 2:

In [149]:
yazi.split()
yazi = "".join(yazi.split())
i = []
harf = []
for harf in range(len(yazi)-1):
    i = (yazi[harf])
    i1 = list(i)
    print(i1)
      
   
    
 

['u']
['l']
['u']
['d']
['a']
['g']
['d']
['e']
['e']
['p']
['l']
['e']
['a']
['r']
['n']
['i']
['n']
['g']
['t']
['e']
['k']
['n']
['i']
['k']
['b']
['i']
['r']
['t']
['o']
['p']
['l']
['u']
['l']
['u']
['k']
['t']
['u']
['r']


### Soru 3:

Sigmoid fonksiyonunu, sigmoid adını verdiğiniz fonksiyonla tanımlayınız.

![sigmoid](sigmoid.jpg)

In [150]:
# Örnek: 
def fonk_ornek(girdi):
    pass #Burası koduna dahil olmayacak.
    sonuc = islem1*islem2/girdi
    return sonuc

### Cevap 3:

In [151]:
import math
def fonk_sigmoid(x):
    sonuc = 1 / (1 + math.exp(-x))
    return sonuc

## Numpy

### Soru 1:

5x5 boyutunda, sıfırlar, birler matrislerini oluşturun.

### Cevap 1:

In [152]:
Birler = np.ones((5,5))
print (Birler)
print()
Sıfırlar = np.zeros((5,5))
print (Sıfırlar)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### Soru 2:

İki farklı 5x5 random sayılardan oluşan iki matris oluşturun. Bu matrisleri matris çarpımı yöntemiyle çarpın

In [153]:
Random1 = np.random.random((5,5))
print(Random1)
print()
Random2 = np.random.random((5,5))
print(Random2)
print()
Carpim = np.dot(Random1,Random2)
print(Carpim)

[[0.00635504 0.44345788 0.61485418 0.78551314 0.31904219]
 [0.17792639 0.17533814 0.63958236 0.61393423 0.83354627]
 [0.17846068 0.30940362 0.91140839 0.63161893 0.37799767]
 [0.61113969 0.4281879  0.49180692 0.12281645 0.09346215]
 [0.95975821 0.06175027 0.18820011 0.90562669 0.38656878]]

[[0.54065991 0.33097873 0.16260353 0.64289128 0.07263188]
 [0.28269853 0.71259695 0.04264541 0.84051608 0.115179  ]
 [0.13264067 0.80208665 0.28569862 0.39556889 0.30340328]
 [0.66754731 0.13033864 0.9218807  0.99765255 0.78821593]
 [0.21895063 0.1334096  0.07432599 0.03831086 0.26965046]]

[[0.80457715 0.95622245 0.94347031 1.41592823 0.94327124]
 [0.82293575 0.88805817 0.84706489 1.15918765 0.93584866]
 [0.80924265 1.14332813 0.91297345 1.37993198 0.92490238]
 [0.6191498  0.93034787 0.37831106 1.07344747 0.36493031]
 [1.25051061 0.68222553 1.07607382 1.66167893 0.95198974]]


### Soru 3:

100 Uzunluklu bir liste oluşturun, önce tek ve çift sayıları döngülerle tek ve çift adlı iki listeye ayırın, bu iki listeyi 5x10 boyutunda iki matris haline getirin.

### Cevap 3:

In [154]:
a = list(range(0,100))
tek_liste = []
cift_liste = []
for i in a:
    if i %2 == 0:
        cift_liste += [i]
    elif i %2 != 0:
        tek_liste +=[i]
print('çift liste: ',cift_liste)
print()
print('tek liste: ',tek_liste)
tek_matris = np.array(tek_liste)
tek_matris.shape = (5,10)
print()
print(tek_matris)
cift_matris = np.array(cift_liste)
cift_matris.shape = (5,10)
print()
print(cift_matris)


çift liste:  [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]

tek liste:  [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]

[[ 1  3  5  7  9 11 13 15 17 19]
 [21 23 25 27 29 31 33 35 37 39]
 [41 43 45 47 49 51 53 55 57 59]
 [61 63 65 67 69 71 73 75 77 79]
 [81 83 85 87 89 91 93 95 97 99]]

[[ 0  2  4  6  8 10 12 14 16 18]
 [20 22 24 26 28 30 32 34 36 38]
 [40 42 44 46 48 50 52 54 56 58]
 [60 62 64 66 68 70 72 74 76 78]
 [80 82 84 86 88 90 92 94 96 98]]


### Soru 0: (Opsiyonel)

Buradaki matematiksel ifadeleri python ile yazmanızı bekliyoruz. Aşağıda yazılan fonksiyonların her biri size ekstra bazı puanlar kazandıracaktır.

![1.](1.jpg "1")

![3.](3.jpg "3")

![2.](2.jpg "2")